import inputSanitizer as ips

payloads = [
    "<!--#exec%20cmd=\"/bin/cat%20/etc/passwd\"-->",
    "<!--#exec%20cmd=\"/bin/cat%20/etc/shadow\"-->",
    "<!--#exec%20cmd=\"/usr/bin/id;-->",
    "<!--#exec%20cmd=\"/usr/bin/id;-->",
    "/index.html|id|",
    "\";id;\"",
    "';id;'",
    ";id;",
    ";id",
    ";netstat -a;",
    "\"|id|\"",
    "'|id|'",
    "|id",
    "|/usr/bin/id",
    "|id|",
    "\"|/usr/bin/id|\"",
    "'|/usr/bin/id|'",
    "|/usr/bin/id|",
    "\"||/usr/bin/id|\"",
    "'||/usr/bin/id|'",
    "||/usr/bin/id|",
    "|id;",
    "||/usr/bin/id;",
    ";id|",
    ";|/usr/bin/id|",
    "\"\\n/bin/ls -al\\n\"",
    "'\\n/bin/ls -al\\n'",
    "\\n/bin/ls -al\\n",
    "\\n/usr/bin/id\\n",
    "\\nid\\n",
    "\\n/usr/bin/id;",
    "\\nid;",
    "\\n/usr/bin/id|",
    "\\nid|",
    ";/usr/bin/id\\n",
    ";id\\n",
    "|usr/bin/id\\n",
    "|nid\\n",
    "`id`",
    "`/usr/bin/id`",
    "a);id",
    "a;id",
    "a);id;",
    "a;id;",
    "a);id|",
    "a;id|",
    "a)|id",
    "a|id",
    "a)|id;",
    "a|id",
    "|/bin/ls -al",
    "a);/usr/bin/id",
    "a;/usr/bin/id",
    "a);/usr/bin/id;",
    "a;/usr/bin/id;",
    "a);/usr/bin/id|",
    "a;/usr/bin/id|",
    "a)|/usr/bin/id",
    "a|/usr/bin/id",
    "a)|/usr/bin/id;",
    "a|/usr/bin/id",
    ";system('cat%20/etc/passwd')",
    ";system('id')",
    ";system('/usr/bin/id')",
    "%0Acat%20/etc/passwd",
    "%0A/usr/bin/id",
    "%0Aid",
    "%22%0A/usr/bin/id%0A%22",
    "%27%0A/usr/bin/id%0A%27",
    "%0A/usr/bin/id%0A",
    "%0Aid%0A",
    "\"& ping -i 30 127.0.0.1 &\"",
    "'& ping -i 30 127.0.0.1 &'",
    "& ping -i 30 127.0.0.1 &",
    "& ping -n 30 127.0.0.1 &",
    "%0a ping -i 30 127.0.0.1 %0a",
    "`ping 127.0.0.1`",
    "| id",
    "& id",
    "; id",
    "%0a id %0a",
    "`id`",
    "$;/usr/bin/id"
]


print("--- osCommandSanitize test ediliyor ---\n")
for payload in payloads:
    try:
        sonuc = ips.osCommandSanitize(payload)
        print(f"Payload: {payload!r} => Sanitized Output: {sonuc}")
    except Exception as e:
        print(f"Payload: {payload!r} => Error: {e}")